name: CI/CD to Railway (Docker)

on:
  push:
    branches:
      - main # deploy when main branch is updated
  workflow_dispatch: # manual trigger option

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        run: railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}

      - name: Link Railway project
        run: railway link ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy Docker container to Railway
        run: |
          railway up --detach --docker
